// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBESFSQo3vWyBn5RlfUWmiTIqsy7qfiGaQ',
    appId: '1:1793612831:web:46f0c6199290718de1492a',
    messagingSenderId: '1793612831',
    projectId: 'sweatsync-82733',
    authDomain: 'sweatsync-82733.firebaseapp.com',
    storageBucket: 'sweatsync-82733.firebasestorage.app',
    measurementId: 'G-XRGDGCHS83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsyEoESr080GHUdFKcNQ7DtGNepjRXD-Q',
    appId: '1:1793612831:android:3ac60fdef76d895ce1492a',
    messagingSenderId: '1793612831',
    projectId: 'sweatsync-82733',
    storageBucket: 'sweatsync-82733.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvpcD6vliv5ZRGbPVf1eJ2srAG7ecEpGs',
    appId: '1:1793612831:ios:2237eea6490f8955e1492a',
    messagingSenderId: '1793612831',
    projectId: 'sweatsync-82733',
    storageBucket: 'sweatsync-82733.firebasestorage.app',
    iosBundleId: 'com.example.sweatsync',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvpcD6vliv5ZRGbPVf1eJ2srAG7ecEpGs',
    appId: '1:1793612831:ios:2237eea6490f8955e1492a',
    messagingSenderId: '1793612831',
    projectId: 'sweatsync-82733',
    storageBucket: 'sweatsync-82733.firebasestorage.app',
    iosBundleId: 'com.example.sweatsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBESFSQo3vWyBn5RlfUWmiTIqsy7qfiGaQ',
    appId: '1:1793612831:web:bb94c1171ccaad93e1492a',
    messagingSenderId: '1793612831',
    projectId: 'sweatsync-82733',
    authDomain: 'sweatsync-82733.firebaseapp.com',
    storageBucket: 'sweatsync-82733.firebasestorage.app',
    measurementId: 'G-G2640LJFJS',
  );
}
